### ISSUE TITLE
Examples showing how to build a graph

### ISSUE THREAD

**Issue by scisci** [kazarena/json-gold#2]
Hi, I'm really interested in this library. Do you have any examples that demonstrate how to build up a json-ld graph? I can see the structures in there just looking for some examples. Thanks!

**Comment by kazarena** [comment]
Hi @scisci,

Thank you for your interest! You are right, I should add some more sophisticated examples.

Working with JSON-LD documents is really easy. You just need to either unmarshall your JSON document into `interface{}` or use a URL directly (see [this example](https://github.com/kazarena/json-gold/blob/master/examples/expand.go) as a template for most of operations), and then invoke one of the standard operations from [JSON-LD API spec](http://www.w3.org/TR/json-ld-api/), i.e. expand, compact, flatten, normalize and so on.

If you are interested in building a graph from JSON-LD document, the easiest way is probably to transform it into triples (using this library) and then use your favourite triple processor. I added a new example here: e5de40227e8d1b93e1af02416da8d9295d189589.

**Comment by scisci** [comment]
Hi @kazarena, thanks thats awesome! Those are good examples for going from json-ld to rdf or some other go structure.

What I need to do, is go the other way: from our internal graph structure (specific to our database) out to json-ld.

Would you suggesting I take our internal graph format (made up of vertexes and edges) and represent each edge relationship using a quad?

```
func NewQuad(subject Node, predicate Node, object Node, graph string)
```

I could then use the json-ld api to write the RDFDataset 

```
func (api *JsonLdApi) FromRDF(dataset *RDFDataset, opts *JsonLdOptions) ([]interface{}, error)
```

or

```
func (jldp *JsonLdProcessor) FromRDF(dataset interface{}, opts *JsonLdOptions) (interface{}, error)
```

And then compact it and Marshal to JSON?

Hopefully that makes sense, I'm still getting my head around json-ld in general.

**Comment by kazarena** [comment]
@scisci, it depends on your internal format. If it's easier to produce an RDF dataset then yes, the methods you mentioned would do. Otherwise, JSON-LD is just normal JSON, that's the beauty of it. The way I would approach this task is as follows (actually, I'm doing it at the moment with one of my proprietary database which is somewhat graph-like:
1. If you data is already in JSON, consider retrofitting JSON-LS schema/context on top of your existing data. The main benefit of this approach is that you don't need to apply any transformations to your data at all. Then either leave it as is (it'll be JSON-LD already) or apply 'Compact' operation to turn it into a new shape.
2. if your data is not in JSON, start with defining a JSON-LD context which describes your data best. It will require a bit of learning if you haven't done it in the past. Once it's ready, produce a dump of your data in JSON and attach your context to it.

That's it!

P.S. No, I woildn't be using `NewQuad(...)`. Consider it internal function until you need to do something which doesn't fit into the standard API functions from JSON-LD spec. In 95% of case that would be enough!
